### ISSUE TITLE
Pre 1.4 firmware offline update failure using firmware v1.4.2!!!

### ISSUE THREAD

**Issue by Assistedevolution** [QIDITECH/QIDI_PLUS4#12]
Doing a first offline update on a new machine, with pre 1.4 firmware. going to latest 1.4.2 release

The printer found the update file on the USB. It got to the following screen (see image below) and does not progress any further. It remains at 0%. (see screen shot).

After 1 hour tried to power cycle the printer but on reboot it just returns to this screen with progress 0%. 

There seems to be no way to get to any other screen. The system is totally unresponsive.

Power cycling, either with or without the USB installed does nothing... it just boots and immediately goes to this screen.

Any help would be appreciated.
![20241020_232559](https://github.com/user-attachments/assets/73689a8e-bfb5-40a0-a4db-50f8b5a4f923)

**Comment by Assistedevolution** [comment]
Note left for a further 8 hours and still showing zero progress. This morning attempted the firmware mksscreen.recovery process as documented in the wiki in case that might be an issues but machine is still stuck at the same screen and is effectively unresponsive.

**Comment by whb0514** [comment]
Please contact our after-sales service to replace a screen for you.

**Comment by Assistedevolution** [comment]
Ok issue resolved. Thanks to Qidi support. 
Problem turned out to be a corrupt RAR extraction, probably our from our side. Qidi sent a pre extracted UI file renamed to mksscreen.recovery which solved this issue, and updated the UI. 
The reason this recovery process had not worked for us before is because our UI file was corrupt. Worth checking if you have a similar problem
