### ISSUE TITLE
Netzwerk per Lan

### ISSUE THREAD

**Issue by Guido-L** [QIDITECH/QIDI_PLUS4#13]
Sobald der Drucker im Netzwerk online ist, gibt es erhebliche Störungen im Netzwerk.
Der Datenfluss wird immer wieder unterbrochen (kein TV, Telefon noch sonst etwas.
Keiner meiner Drucker macht dieses Problem.

**Comment by QIDITECH** [comment]
Try to remove the wireless card from the motherboard and install it on the USB port on the top of the printer.
If there is no improvement, please contact customer service to replace the wireless card.

**Comment by Guido-L** [comment]
Danke für den Tipp. Leider hat es nicht geholfen und ich habe mich dann mit den Kundendienst in Verbindung gesetzt. Warte jetzt auf eine Antwort.
