### ISSUE TITLE
Plus 4 arrived without a screen

### ISSUE THREAD

**Issue by Wayfst** [QIDITECH/QIDI_PLUS4#14]
While unboxing I found an empty box for the screen. Email several times no response, anyone have an email that works?

**Comment by Rizadium** [comment]
I used Plus4support@qidi3d.com

**Comment by QIDITECH** [comment]
You can try to contact us at email, [Plus4support@qidi3d.com](mailto:Plus4support@qidi3d.com), [Plus4Ams@qidi3d.com](mailto:Plus4Ams@qidi3d.com), [karl@qd3dprinter.com](mailto:karl@qd3dprinter.com).

**Comment by Wayfst** [comment]
I did

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by QIDITECH** [comment]
If you still haven't received a reply, please tell me your email address, we will take the initiative to contact you.
