### ISSUE TITLE
Remove update function in Fluidd

### ISSUE THREAD

**Issue by FxWoody** [QIDITECH/QIDI_PLUS4#18]
Since the klipper version is modify for the Printer, the Fluidd "update" function should be removed or locked.
I had a notification message in the dashboard to update and did it but ended up "bricking" my printer or causing errors and now printer is not working anymore.
Need info how to fix this :)
![klipper-error](https://github.com/user-attachments/assets/0136d2dd-86da-4eea-99a8-667cac91d5c6)
![klipper-update](https://github.com/user-attachments/assets/43a32265-8739-45d2-9678-0090d985ab3c)

**Comment by QIDITECH** [comment]
We have not enabled this function, please confirm whether it is caused by your operation.

**Comment by FxWoody** [comment]
The update function in Fluidd is working from the bottom of the settings page ... i even had a notification that came up in the upper bar. Was showing updates needed so i did :(

**Comment by QIDITECH** [comment]
The version of fluidd we use is not very different from the official latest version, if it is only updated fluidd, it should not affect the use. Be careful not to update the moonraker or klipper, as this will render the printer unusable.
Maybe you can find the configuration in the moonraker.cfg file in the configuration to turn it off.
Or you can update the firmware offline to override the original version.
