### ISSUE TITLE
Info request/tooltips

### ISSUE THREAD

**Issue by WyldCFH** [QIDITECH/QIDI_PLUS4#19]
Is there a way to get some expanded info or tooltips in the Fluidd interface to explain what Sound, Beeper and ctlyd switches do?

<img width="271" alt="image" src="https://github.com/user-attachments/assets/40100bf9-c50c-4d98-95fe-584d55e874a6">

**Comment by QIDITECH** [comment]
The current version of fluidd does not support this.

**Comment by WyldCFH** [comment]
Can this info be added to the Wiki then? 
Or, just put the explanation here so the next person that comes looking for it can find it.

**Comment by QIDITECH** [comment]
Sound and Beeper: Used to control a buzzer that will sound an alert at zero and the end of printing
Ctlyd: For the control of piezoelectric plates
Caselight: Used for LED lights inside the case

**Comment by WyldCFH** [comment]
Thank you for the explanation.
