### ISSUE TITLE
"The UI version does not match the firmware please check for updates " on screen

### ISSUE THREAD

**Issue by Channel-VR** [QIDITECH/QIDI_PLUS4#24]
Hi,  after updating to version V1.4.3 i get this message : "The UI version does not match the firmware please check for updates "

Printer said update was successful but apparently something went wrong

![20241110_192842](https://github.com/user-attachments/assets/0c5826b8-033c-4723-a99c-429c4e2ede34)
 .

**Comment by QIDITECH** [comment]
UI update failed, please try to update firmware again.
