### ISSUE TITLE
Bug: Lost connection to the webcam

### ISSUE THREAD

**Issue by gmueller2000privat** [QIDITECH/QIDI_PLUS4#25]
I am constantly loosing connection to the webcam. 

I think it does happen when I restart a printjob from the display or after canceling a print through the display.

Rebooting of the machine brings the webcam back

**Comment by gmueller2000privat** [comment]
I observed a static spark when I touched the printer and afterwards the webcam went offline. Might be caused by my shoes. Will watch this and report it

**Comment by QIDITECH** [comment]
I think there's been some damage to the camera wiring.
Please contact after-sales service to replace the camera.

**Comment by gmueller2000privat** [comment]
Different shoes today, no sparks so far ... I think I call sketcher's support ;)
