### ISSUE TITLE
Wrong download link for release 1.6.0

### ISSUE THREAD

**Issue by 1000000v** [QIDITECH/QIDI_PLUS4#30]
Hi,

I just wanted to mention that your link in release description is invalid.

Release description link: `https://github.com/QIDITECH/QIDI_PLUS4/releases/download/Plus4_V1.6.0/Plus4_V1.6.0.rar`
Correct link: `https://github.com/QIDITECH/QIDI_PLUS4/releases/download/Plus4_v1.6.0/PLUS4_V1.6.0.rar`

Note: `Plus4` vs `PLUS4`.

1MV

**Comment by whb0514** [comment]
Thanks for your reminding, this issue has been fixed.
