### ISSUE TITLE
Issues 32 and 33 are not visable for everyone

### ISSUE THREAD

**Issue by Ken6432** [QIDITECH/QIDI_PLUS4#35]
I logged issues 32 and 33 from my phone.  I am unable to see them from there, but can see them on my computer.  Another user says they cannot get to their links and receives a 404 error.  Can Qidi please confirm that they can see the two issues?  If not, I will  resubmit them from my computer.  The two issues are related to the 1.6.0 firmware update and are very important

**Comment by budfox22** [comment]
I see only this one from you

**Comment by budfox22** [comment]
I see 32 and 33 issue from you.

**Comment by Ken6432** [comment]
Thanks!  I contacted GitHub support and they removed some sort of lock that was on my account

**Comment by Ken6432** [comment]
My other issues should be visible now that my GitHub account was unlocked
