### ISSUE TITLE
Setting the temperature of the chamber heating fan to anything lower than 45 degrees craches klipper

### ISSUE THREAD

**Issue by nilsolovp** [QIDITECH/QIDI_PLUS4#36]
Edit: Plus4_V1.6.0 Version Release
As my printer is in a cold place I use the chamber heater to get a nice temperature for PLA. Usually 25-30 degrees. 
But if a file is slized with anything other than 45 or 60 degrees on the chamber heater it will crash the firmware.

**Comment by nilsolovp** [comment]
![IMG_9210](https://github.com/user-attachments/assets/ae848d19-4acc-4a96-8154-f2cc0399a7ee)

**Comment by QIDITECH** [comment]
Under normal sealed printing conditions, a hot bed of 60 ° C can make the chamber temperature reach 35-40 ° C. Therefore, we set a minimum chamber temperature of 45 ° C. Even in a cold environment, as long as the hot bed is preheated for a period of time, I think the chamber temperature is enough to print PLA normally. 
We do not recommend that you turn on the chamber heating, but you can turn off the circulating fan to increase the temperature in the chamber.
![image](https://github.com/user-attachments/assets/ff07be41-31f6-4d27-ac0e-58d4865fad5d)

**Comment by nilsolovp** [comment]
It’s true as you said that the heat bed will eventually heat the chamber but I use the heater fan as a circulation fan for the low temperature, to make sure it’s a stable temperature controlled environment.

**Comment by QIDITECH** [comment]
Sorry, for security reasons, the new version of the firmware will no longer support you in this way. You can only achieve your needs in other ways.

**Comment by nilsolovp** [comment]
I’m aware of the issue where the control for the heater overheat for the 110v market and the firmware fixes this error in design. 
Lucky for me I’m not effected by this. 
But I live in a country that’s cold in the winter and I liked the idea of maximizing the circulation of the air in the chamber when it eventually reaches a good and steady temperature. And to be able to have temperature controller and heater if it’s needed was one of the features that made me buy this printer. 
And this feature I lost due to safety reasons.

**Comment by whb0514** [comment]
> [heater_generic chamber]
heater_pin:U_1:PC8
max_power:0.4
sensor_type:NTC 100K MGB18-104F39050L32
sensor_pin:U_1:PA1
control = pid
pid_Kp=63.418 
pid_Ki=1.342 
pid_Kd=749.125
min_temp:-100
max_temp:70
target_min_temp:45
target_max_temp:65
heat_with_heater_bed:True
heat_with_heater_bed_tem_add:25

You can find the target_min_temp in the printer.cfg file, which limits the minimum heating temperature, please modify it to what you need.
