### ISSUE TITLE
"Webcam intermittently stops with 'Error Timelapse' on Fluidd"

### ISSUE THREAD

**Issue by budfox22** [QIDITECH/QIDI_PLUS4#38]
Hello everyone,

I would like to report that sporadically the webcam unexpectedly stops working, displaying the message "Error Timelapse" on Fluidd, and it becomes impossible to view the video.

Each time, it is necessary to restart the "Webcamd" service from Fluidd to restore video functionality.

This issue has been present since the first firmware release and is still occurring on version 1.6.0.

Thank you.

**Comment by QIDITECH** [comment]
Please contact after-sales service to replace the camera.
