### ISSUE TITLE
Release pinout diagrams for mainboard and toolboard

### ISSUE THREAD

**Issue by vega-d** [QIDITECH/QIDI_PLUS4#7]
Hi. Could you kindly publish the pdf files for pin mappings of the x plus 4 mainboard and toolhead pcbs? Thank you a lot for your openness and support of modding.

**Comment by whb0514** [comment]
[X-7 V1.1_001 PIN.pdf](https://github.com/user-attachments/files/17348915/X-7.V1.1_001.PIN.pdf)
